# Generated by Django 3.2.25 on 2024-11-29 16:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a category of the request (3D Design, 2D Design, etc.)', max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(help_text='Type a brief description of the interior', max_length=1000)),
                ('plan', models.ImageField(help_text='Select a cover for this request', null=True, upload_to='images/')),
                ('creationDate', models.DateField(default=datetime.date.today)),
                ('design', models.ImageField(null=True, upload_to='images/')),
                ('status', models.CharField(blank=True, choices=[('n', 'New'), ('a', 'Accepted for work'), ('d', 'Done')], default='n', max_length=1)),
                ('category', models.ForeignKey(help_text='Выберите категорию заявки', null=True, on_delete=django.db.models.deletion.SET_NULL, to='interior.category')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patronym', models.CharField(blank=True, max_length=160, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
