# Generated by Django 3.2.25 on 2024-12-01 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interior', '0002_query_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='query',
            options={'ordering': ['-creationDate']},
        ),
    ]
