# Generated by Django 3.2.25 on 2024-12-03 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior', '0003_alter_query_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Введите категорию заявок (2Д дизайн, 3Д дизайн и т.д.)', max_length=200, unique=True),
        ),
        migrations.RemoveField(
            model_name='query',
            name='category',
        ),
        migrations.AddField(
            model_name='query',
            name='category',
            field=models.ManyToManyField(help_text='Выберите категорию заявки', to='interior.Category'),
        ),
        migrations.AlterField(
            model_name='query',
            name='description',
            field=models.TextField(help_text='Пропишите краткое описание интерьера', max_length=1000),
        ),
        migrations.AlterField(
            model_name='query',
            name='plan',
            field=models.ImageField(help_text='Выберите обложку для заявки', null=True, upload_to='images/'),
        ),
    ]
